### PR TITLE
Remove dependency on prod-tmp.dev.funcx.org and manage dns with k8s

### PR DESCRIPTION
**Pull request by ghost**
Story details: https://app.shortcut.com/funcx/story/10969

This adds config and make targets to install the external dns controller in EKS.

### CODE REVIEW

**Comment by sirosen** [comment]
Are there new IAM Roles for this? I'm a little bit confused about who/what creates them and how they are used.
I'm looking at the external-dns AWS tutorial [and in particular their example manifest](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md#manifest-for-clusters-with-rbac-enabled), but I'm not clear on whether or not this means that EKS is responsible for the Role.

My other major question is whether or not there's a TXT record or something similar at play?
I'm not clear on what that `--txt-owner-id` argument is doing.


I was able to basically read all of this and understand it well enough except for `cloudformation/external-dns.yaml`. 👍 for the new make targets!
I'm still trying to understand that on file though.

<details><summary>aside on file and dir names</summary>

It isn't new in this PR, but I definitely get confused by us having a directory named `cloudformation/` which has non-CFN YAML files in it. Maybe we would benefit from some structure like
```
eks-config/
  Makefile
  cloudformation/
    funcx.yaml
  external-dns.yaml
```
</details>

**Comment by sirosen** [comment]
Trying to break down my lack of understanding of this "manifest" file a bit:

---

What consumes the manifest in production? Does this go into eksctl or directly into kubectl?

---

Is there significant detail in the preamble for me to grasp?

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-dns
```
I'm assuming the first line says "kubernetes API version / manifest version is v1".
Where can I read about these other fields? The content suggests to me that something is being provisioned in the k8s cluster with a name of `external-dns`, but I don't know what.

---

What is the `ClusterRole` section saying?

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list"]
```

There are clearly permissions for "nodes", "services", and "pods" in here. Who is being given what permissions here? The `apiGroups: [""]` values are particularly mysterious.

---

What does the `ClusterRoleBinding` section mean?

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: external-dns-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: default
```

`external-dns` is used here, and somehow being associated with two different objects here? And the name of the binding (am I following?) is `external-dns-viewer`, is that right?

---

The deployment section at the end somehow needs to use the prior sections.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
```
So the name of the deployment is also `external-dns`.

Having `spec.template.spec.serviceAccountName: external-dns` seems to make sense based on what I follow. (Ignoring that I don't know what some parts of that path mean). But what is `spec.selector.matchLabels`?

---

After listing all of those things that I don't know, and could use help understanding, the part at the very end is the most understandable. It's some set of arguments and parameters to the `external-dns` app provided by the `bitnami/external-dns:0.7.1` image.

**Review by BenGalewsky — APPROVED** [review]
Looks like a welcome change.

**Comment by ghost** [comment]
> What consumes the manifest in production? Does this go into eksctl or directly into kubectl?

This is `kubectl`.  The line here adds it to the `Makefile` for install external dns:
```
kubectl apply -f external-dns.yaml --namespace kube-system
```

> Is there significant detail in the preamble for me to grasp?
> 
> ```yaml
> apiVersion: v1
> kind: ServiceAccount
> metadata:
>   name: external-dns
> ```
> 

No, this is mostly copied from [https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/aws.md]

> I'm assuming the first line says "kubernetes API version / manifest version is v1". Where can I read about these other fields? The content suggests to me that something is being provisioned in the k8s cluster with a name of `external-dns`, but I don't know what.

This is k8s api and other fields can be read about in [k8s docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#serviceaccount-v1-core).  `externa-dns` is a controller to config route53 according to the ingress controller config.

> What is the `ClusterRole` section saying?
> 
> ```yaml
> apiVersion: rbac.authorization.k8s.io/v1beta1
> kind: ClusterRole
> metadata:
>   name: external-dns
> rules:
> - apiGroups: [""]
>   resources: ["services"]
>   verbs: ["get","watch","list"]
> - apiGroups: [""]
>   resources: ["pods"]
>   verbs: ["get","watch","list"]
> - apiGroups: ["extensions"]
>   resources: ["ingresses"]
>   verbs: ["get","watch","list"]
> - apiGroups: [""]
>   resources: ["nodes"]
>   verbs: ["list"]
> ```
> 
> There are clearly permissions for "nodes", "services", and "pods" in here. Who is being given what permissions here? The `apiGroups: [""]` values are particularly mysterious.
> 

This is defining a role in the k8s cluster that has access to execute certain `verbs` on some k8s resources.  See [docs here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#clusterrole-v1beta1-rbac-authorization-k8s-io)

> What does the `ClusterRoleBinding` section mean?
> 
> ```yaml
> apiVersion: rbac.authorization.k8s.io/v1beta1
> kind: ClusterRoleBinding
> metadata:
>   name: external-dns-viewer
> roleRef:
>   apiGroup: rbac.authorization.k8s.io
>   kind: ClusterRole
>   name: external-dns
> subjects:
> - kind: ServiceAccount
>   name: external-dns
>   namespace: default
> ```
> 
> `external-dns` is used here, and somehow being associated with two different objects here? And the name of the binding (am I following?) is `external-dns-viewer`, is that right?

Yes, this is binds the role with the `external-dns` account that should be setup by the `eksctl` `wellKnownPolicies` flag.

> 
> The deployment section at the end somehow needs to use the prior sections.
> 
> ```yaml
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: external-dns
> ```
> 
> So the name of the deployment is also `external-dns`.
> 
> Having `spec.template.spec.serviceAccountName: external-dns` seems to make sense based on what I follow. (Ignoring that I don't know what some parts of that path mean). But what is `spec.selector.matchLabels`?
> 
> After listing all of those things that I don't know, and could use help understanding, the part at the very end is the most understandable. It's some set of arguments and parameters to the `external-dns` app provided by the `bitnami/external-dns:0.7.1` image.

Exactly.

**Pull request merged**
